name: 'Checkout PEP 440'
description: 'Checkout a Git repository using a PEP 440 version specifier. Requires Python with packaging installed.'
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true
  specifier:
    description: 'The PEP 440 version specifier to match against.'
    required: true
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: true
  rest-token:
    description: 'The Github authentication token to use to access the REST API.'
    required: true
  submodules:
    description: 'Should submodules be cloned. false|true|recursive'
    default: 'false'
outputs:
  ref:
    description: 'The tag that was checked out.'
    value: ${{ steps.find-tag.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: Find Matching Tag
      id: find-tag
      shell: bash
      env:
        REST_TOKEN: ${{ inputs.rest-token }}
      run: |
        tag=$(python -c "import sys; sys.path.append(r\"${{ github.action_path }}\"); import find_tag; print(find_tag.find_tag('${{ inputs.repository }}', '${{ inputs.specifier }}'))")
        echo "tag=$tag" >> "$GITHUB_OUTPUT"

    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ steps.find-tag.outputs.tag }}
        path: ${{ inputs.path }}
        submodules: ${{ inputs.submodules }}
